bind = "0.0.0.0:28019"

[engines]
google = { weight = 1.05 }
bing = { weight = 1.0 }
brave = { weight = 1.25 }

[engines.marginalia]
args = { profile = "corpo", js = "default", adtech = "default" }
weight = 0.15
